#!/usr/bin/env bash
# ----- RUN SCRIPT AS SUPER USER -----
# Installs 'nginx' on your server with the following requirements
#	- Listens to port 80
#	- Returns a page containing the string 'Hello World' when querying
#	  it root directory

# Update the package list from all configured sources
apt-get update;
# Install the 'nginx' handsfree from apt store
apt-get install nginx -y;
ufw allow 'Nginx HTTP';

mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/custom_404.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html;

	server_name _;
	add_header X-Served-By $(eval hostname);
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /custom_404.html;
	location /custom_404.html {
	    root /etc/nginx/html;
	    internal;
    	}
}" > /etc/nginx/sites-available/default

service nginx restart
