#!/usr/bin/env bash
# Script that debugs a web server that can't listen to port 80
sudo rm -rf /etc/nginx/sites-enabled
sudo ln -s /etc/nginx/sites-available /etc/nginx/sites-enabled;
sudo service nginx restart;
