#!/usr/bin/env bash
# Script that debugs a web server that can't listen to port 80
sudo sed -i 's/listen 8080/listen 80/' /etc/nginx/sites-enabled/default;
sudo sed -i 's/listen \[::\]:8080/listen [::]:80/' /etc/nginx/sites-enabled/default;
sudo service nginx restart;
