#!/usr/bin/env bash
# Displays the content of the file '/etc/passwd',  using the
# 'while' loop + 'IFS'.

file="/etc/passwd"
while IFS= read -r line;
do
	username=$(echo "$line" | cut -d ":" -f1)
	pass=$(echo "$line" | cut -d ":" -f2)
	uid=$(echo "$line" | cut -d ":" -f3)
	gid=$(echo "$line" | cut -d ":" -f4)
	uid_info=$(echo "$line" | cut -d ":" -f5)
	home=$(echo "$line" | cut -d ":" -f6)
	path=$(echo "$line" | cut -d ":" -f7)

	echo "The user $username is part of the $gid gang, lives in $home and rides $path. $uid's place is protected by the passcode $pass, more info about the user here: $uid_info"

done < "$file"
