#!/usr/bin/env bash
# Displays the content of the file '/etc/passwd',  using the
# 'while' loop + 'IFS'.

file="/etc/passwd"
while IFS= read -r line;
do
	username=$(echo "$line" | cut -d ":" -f1)
	pass=$(echo "$line" | cut -d ":" -f2)
	U_ID=$(echo "$line" | cut -d ":" -f3)
	gid=$(echo "$line" | cut -d ":" -f4)
	uid_Info=$(echo "$line" | cut -d ":" -f5)
	HOME=$(echo "$line" | cut -d ":" -f6)
	PATH=$(echo "$line" | cut -d ":" -f7)

	echo "The user $username is part of the $gid gang, lives in $HOME and rides $PATH. $uid's place is protected by the passcode $pass, more info about the user here: $U_ID_Info"

done < "$file"
