#!/usr/bin/env bash
# Displays 'Best School' 10 times iteratively, but displays 'Hi' for the
# 9th iteration.

i=1
while [ $i -le 10 ];
do
	if [ $i == 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
