#!/bin/bash
# Sets up a server firewall using 'ufw' to block all incoming traffic,
# except on TCP port 22, 443 and 80
sudo apt-get update;
sudo apt-get install ufw -y;
sudo ufw default deny incoming;
sudo ufw default allow outgoing;
sudo ufw allow 22/tcp;
sudo ufw allow 80/tcp;
sudo ufw allow 443/tcp;
sudo ufw enable -y;
