#!/bin/bash
# Sets up a server firewall using 'ufw' to block all incoming traffic,
# except on TCP port 22, 443 and 80
apt-get update && apt-get install ufw -y;
ufw default deny incoming;
ufw default allow outgoing;
ufw allow in 22/tcp;
ufw allow 80/tcp;
ufw allow 443/tcp;
ufw enable -y;

